import type { BufferSource } from '@/editor/model/types'
import type { Locale } from '@/i18n/locale'

const lines: Record<Locale, string[]> = {
  en: [
    "*help.txt*          Moisés' portfolio          Last change: 2026 Sep 28",
    '',
    '                    PORTFOLIO USER MANUAL',
    '',
    'This portfolio is disguised as Vim, but you do not need to know Vim:',
    'tabs, links and form fields all work with the mouse or a tap.',
    '',
    '==============================================================================',
    '1. Tabs                                                          *help-tabs*',
    '',
    '  gt  /  gT              next / previous tab',
    '  {n}gt                  go to tab {n}, e.g. 3gt',
    '  :e {file}              open {file} in a tab (<Tab> completes)',
    '  :q                     close the current tab',
    '  <Space>e  or  -        show / hide the file tree',
    '  <Esc>                  leave the tree, back to the editor',
    '',
    'Sections: |readme| |experience| |projects| |stack| |contact| |cv|',
    '',
    '==============================================================================',
    '2. Moving around                                              *help-motions*',
    '',
    '  j  k  h  l             down, up, left, right (arrows work too)',
    '  w  /  b                next / previous word',
    '  0  /  $                start / end of line',
    '  gg  /  G               first / last line',
    '  {count}{motion}        repeat a motion, e.g. 5j',
    '  :{n}                   jump to line {n}',
    '  CTRL-D  /  CTRL-U      half a page down / up',
    '  <Enter>  or  gx        follow the link under the cursor',
    '',
    '==============================================================================',
    '3. Searching                                                   *help-search*',
    '',
    '  /{pattern}             search forward',
    '  n  /  N                next / previous match',
    '  :noh                   clear the highlight',
    '',
    '==============================================================================',
    '4. Contact form                                               *help-contact*',
    '',
    '  i                      start typing in the field under the cursor',
    '  <Esc>                  back to normal mode',
    '  :w                     send the message',
    '',
    '==============================================================================',
    '5. Options                                                     *help-options*',
    '',
    '  :set lang=es           cambiar a español',
    '  :set background=light  light theme (:set background=dark to go back)',
    '  :set relativenumber    relative line numbers (:set norelativenumber)',
    '',
    '==============================================================================',
    '6. Shortcuts                                                 *help-shortcuts*',
    '',
    '  ?                      open this help',
    '  :contact  :cv  :github  :linkedin',
    '',
    'vim:tw=78:ft=help:norl:',
  ],
  es: [
    '*help.txt*        Portafolio de Moisés        Último cambio: 2026 Sep 28',
    '',
    '                    MANUAL DE USO DEL PORTAFOLIO',
    '',
    'Este portafolio está disfrazado de Vim, pero no necesitas saber Vim:',
    'las tabs, los enlaces y el formulario funcionan con el mouse o un toque.',
    '',
    '==============================================================================',
    '1. Tabs                                                          *help-tabs*',
    '',
    '  gt  /  gT              tab siguiente / anterior',
    '  {n}gt                  ir a la tab {n}, por ejemplo 3gt',
    '  :e {file}              abrir {file} en una tab (<Tab> autocompleta)',
    '  :q                     cerrar la tab actual',
    '  <Space>e  o  -         mostrar / ocultar el árbol de archivos',
    '  <Esc>                  salir del árbol y volver al editor',
    '',
    'Secciones: |readme| |experience| |projects| |stack| |contact| |cv|',
    '',
    '==============================================================================',
    '2. Moverse                                                    *help-motions*',
    '',
    '  j  k  h  l             abajo, arriba, izquierda, derecha (o las flechas)',
    '  w  /  b                palabra siguiente / anterior',
    '  0  /  $                inicio / fin de línea',
    '  gg  /  G               primera / última línea',
    '  {count}{motion}        repetir un movimiento, por ejemplo 5j',
    '  :{n}                   saltar a la línea {n}',
    '  CTRL-D  /  CTRL-U      media página abajo / arriba',
    '  <Enter>  o  gx         seguir el enlace bajo el cursor',
    '',
    '==============================================================================',
    '3. Buscar                                                      *help-search*',
    '',
    '  /{pattern}             buscar hacia adelante',
    '  n  /  N                coincidencia siguiente / anterior',
    '  :noh                   quitar el resaltado',
    '',
    '==============================================================================',
    '4. Formulario de contacto                                     *help-contact*',
    '',
    '  i                      escribir en el campo bajo el cursor',
    '  <Esc>                  volver al modo normal',
    '  :w                     enviar el mensaje',
    '',
    '==============================================================================',
    '5. Opciones                                                    *help-options*',
    '',
    '  :set lang=en           switch to English',
    '  :set background=light  tema claro (:set background=dark para volver)',
    '  :set relativenumber    números de línea relativos (:set norelativenumber)',
    '',
    '==============================================================================',
    '6. Atajos                                                    *help-shortcuts*',
    '',
    '  ?                      abrir esta ayuda',
    '  :contact  :cv  :github  :linkedin',
    '',
    'vim:tw=78:ft=help:norl:',
  ],
}

export function help(locale: Locale): BufferSource {
  return { id: 'help', name: 'help.txt', filetype: 'help', lines: lines[locale] }
}
